# permissions for end users to view appservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appservice-viewer-role
rules:
- apiGroups:
  - gramola.atarazana.com
  resources:
  - appservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gramola.atarazana.com
  resources:
  - appservices/status
  verbs:
  - get
